language: node_js
sudo: false
before_install:
  - npm install -g npm@2.11
  - npm set registry https://repository.fit.cvut.cz/npm
  - 'npm set "//repository.fit.cvut.cz/:_authToken=${NPM_TOKEN}"'
install:
  - gem install compass sass-globbing
  - npm install
script:
  - true  # do nothing
after_success:
  - script/travis-npm-publish.sh
notifications:
  email: false
  slack: rozvoj-fit:oIJm1tjEXhiJLDHvp2ATCZIT
env:
  global:
    secure: UgTXgzJc9W9Ya3xH6N1jmRD7ojUOnWze5sNrr/7elAfC6asmERQJj9vK3A7Oby0DQekEB1WTH4iBA1uh8/cO/6G5GZqfoDq21acJVW5OtouPWwZSNc7/YUvMHiin7WlhBh9iGZBaZ0fzkaqrOv5daxhVApPwV3uFwECPey4HytA=  # NPM_TOKEN
