language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    - secure: C4uIU2zCWERoPQR41yCYI05LL4joqdAcD1yrLAzPq8wKgWAq3T/vdmEm4ePEWM+mNcXW3aHXAj/1tjFNvamZ6kzf7c1+E2ubbqRKEGQsk7g5PJM/IaCAF3z6VYhK8+QktsbgZHDeG6+x1nU/oQf9g+tLIwK474gtfkSP7C3NMyg=  # GH_TOKEN
